apiVersion: v1
kind: pod
metadata:
  name: trail6
  labels:
    env: dev
    app: nginx
    version: "1.0"
spec:
  containers:
    - name: httpd
      image: apache
      resourses:
        limits:
          cpu: "500m"
          memory: "1Gi"
      ports:
        - containerPort: 80