apiVersion: v1
kind: Pod
metadata:
  name: trail4
spec:
  containers:
    - name: jenkinscontainer
      image: jenkins/jenkins:jdk17
      resources:
        requests:
          cpu: 500m
          memory: 500Mi
        limits:
          cpu: 1000m
          memory: 1Gi
      ports: 
        - containerPort: 8080