apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: trail7-rs
  labels:
    name: trail1
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        env: dev
        app: nginx
        version: "1.0"
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 80

